slug: amex-activity
version: v1
name: American Express
author: Jason Godson
summary: Template for American Express activity CSV exports.
source:
  institution: American Express
  csv_export_path: Account Activity -> Download CSV
