slug: wealthsimple-credit-card
version: v2
name: Wealthsimple Credit Card
author: Jason Godson
summary: Template for Wealthsimple credit card statement CSV exports.
source:
  institution: Wealthsimple
  csv_export_path: Log In -> Documents -> Download CSV
